Closing a channel should cleanup recorded auto-delete queues
rabbitmq/rabbitmq-java-client pull request #669
Opened 2021-02-16 04:32 UTC by vikinghawk

## Proposed Changes

Please describe the big picture of your changes here to communicate to the
RabbitMQ team why we should accept this pull request. If it fixes a bug or
resolves a feature request, be sure to link to that issue.

A pull request that doesn't explain **why** the change was made has a much
lower chance of being accepted.

If English isn't your first language, don't worry about it and try to
communicate the problem you are trying to solve to the best of your abilities.
As long as we can understand the intent, it's all good.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [ ] I have read the `CONTRIBUTING.md` document
- [ ] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

2021-02-16 06:29 UTC, michaelklishin commented
CI reported a lot of failures like this:

```
04:35:02.605 [rabbitmq-connection-shutdown-amqp://guest@127.0.0.1:5672/] ERROR c.r.c.impl.ForgivingExceptionHandler - Caught an exception when recovering topology Caught an exception while recovering consumer amq.ctag-z7lKh0mMzJkcQtj0Uw5elg: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue '-2745730218113755' in vhost '/', class-id=60, method-id=20)
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering consumer amq.ctag-z7lKh0mMzJkcQtj0Uw5elg: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue '-2745730218113755' in vhost '/', class-id=60, method-id=20)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverConsumer(AutorecoveringConnection.java:821)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverTopology(AutorecoveringConnection.java:681)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:583)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.lambda$addAutomaticRecoveryListener$3(AutorecoveringConnection.java:509)
	at com.rabbitmq.client.impl.AMQConnection.notifyRecoveryCanBeginListeners(AMQConnection.java:808)
	at com.rabbitmq.client.impl.AMQConnection.doFinalShutdown(AMQConnection.java:785)
	at com.rabbitmq.client.impl.nio.NioLoop.lambda$dispatchShutdownToConnection$2(NioLoop.java:305)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue '-2745730218113755' in vhost '/', class-id=60, method-id=20)
```

This can be due to our recent test suite changes as I'm running into an unrelated error in `master`.

2021-02-16 07:18 UTC, michaelklishin commented
```
[ERROR]   ConnectionRecovery>BrokerTestCase.tearDown:94->BrokerTestCase.closeChannel:171 » ConcurrentModification
[ERROR]   ConnectionRecovery.consumersAreRemovedFromConnectionWhenChannelIsClosed:792 » ConcurrentModification
```

is an error specific to this branch.

2021-02-16 07:34 UTC, michaelklishin commented
I used

```
./mvnw verify -P '!setup-test-cluster',use-nio -Dtest-broker.A.nodename=rabbit@$(hostname -s) -Drabbitmqctl.bin=rabbitmqctl -Dit.test=ConnectionRecovery
```

to run the suite.

2021-02-16 10:20 UTC, acogoluegnes requested changes

2021-02-16 10:20 UTC, acogoluegnes commented on src/main/java/com/rabbitmq/client/impl/recovery/AutorecoveringChannel.java
> +                this.deleteRecordedConsumer(consumerTag);
Iterating over the consumer tags set and removing them in `deleteRecordedConsumer(String)` causes a `ConcurrentModificationException`. Maybe moving the removal to the caller is a solution (and using an iterator and `Iterator#remove()` in the iteration). Not super-DRY, but it should work. The channel instance will be GC-ed in the case of the closing anyway.

2021-02-17 07:42 UTC, acogoluegnes approved these changes

2021-02-17 07:42 UTC, merged

2021-02-17 07:50 UTC, acogoluegnes commented
Thanks!